# ==============================================================================
# Kong 3.4 — Configuração Declarativa Estática (Fix Final - RSA Public Key)
# ==============================================================================

_format_version: '3.0'
_transform: true

services:
    - name: order-service
      url: http://order-service:8080
      routes:
          - name: order-api-route
            paths: [/api/v1/orders]
            strip_path: false
          - name: order-admin-route
            paths: [/order-service/admin]
            strip_path: true
      plugins:
          - name: jwt
            config:
                key_claim_name: iss
                claims_to_verify: [exp]

    - name: wallet-service
      url: http://wallet-service:8081
      routes:
          - name: wallet-api-route
            paths: [/api/v1/wallets]
            strip_path: false
          - name: wallet-admin-route
            paths: [/wallet-service/admin]
            strip_path: true
      plugins:
          - name: jwt
            config:
                key_claim_name: iss
                claims_to_verify: [exp]

consumers:
    - username: keycloak-realm-consumer
      jwt_secrets:
          - key: "http://keycloak:8080/realms/orderbook-realm"
            algorithm: RS256
            rsa_public_key: |
              -----BEGIN PUBLIC KEY-----
              MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArazAYGBIuiuzGNkxEjDq
              FGG9Wh3yEYwcLfdKkkUfhYP2snxl//2odvJODXEduvWNGEcLZ6Od0qdTTOLF0yC9
              7+kzfuE43iTGJqV/Yf4DVG/NFY9aT04LFwbVPJuG3pzLTK50Sh8tJxwZ/7cMsOE7
              ErDgcHr1yCzKjuu/2XMy+VmWRPtRnxaE1NkUi4dsdB0g9MFyY/q2j3YT0fg4RTvw
              DVZ/ZYxACrf2yBs5zt6NWeVLDIibVtCbJbRdw7NuTLCb1W6koSnRMbsEeTm6NrRe
              BMgmvjGdvvSuQ6AV3J/5BXQJLfL0w7CCcGk8ARyocTTwDskEv8NGrLZ6rsrrityK
              mQIDAQAB
              -----END PUBLIC KEY-----
          - key: "BhUNo0PtUXhAuYU3g43MUr22Sr-igi37_J3MtVa4kMo"
            algorithm: RS256
            rsa_public_key: |
              -----BEGIN PUBLIC KEY-----
              MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA9eifVbu0B1fm+Pa/xwzu
              uhqwLjof4yaIcpSiEU0GuIv+M+qNkb3wWa6Pn76kKmPKEzE1s2yOuFP+tb4ShKD8
              JJX2OcjN548hDUpm35050uQCz07/2ARHx8961YHjxD7NTeal+Qi4gKrfSX+iVcml
              tLYfe2flhiKmNVVjnEirmb3mDemSnjbEm7jjIU3aA44zfV2jWgURusVBpPnYMygt
              M6QUlrJfgqsflftpwqcMeoC1MNREV7GTeEtLeAzPgkTY5O67iEBX1YIN8kMLR+dI
              rd42ssw2+WLzT11coJktIZ1x6Iq0RA4cVdnv0tEWq3lcOpVwcCNjoq2R6NQP767B
              VQIDAQAB
              -----END PUBLIC KEY-----
