package com.vibranium.contracts;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.vibranium.contracts.events.order.MatchExecutedEvent;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import java.util.stream.IntStream;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Testes dedicados ao {@link MatchExecutedEvent} — o evento mais crítico
 * da plataforma, pois dispara a liquidação financeira irreversível.
 *
 * Cenários cobertos:
 * - Match total (buyer e seller com quantidades iguais)
 * - Match parcial (volumes diferentes — apenas matchAmount é transacionado)
 * - Imutabilidade do record
 * - Unicidade dos matchIds em alta carga (5000 trades/s)
 * - Integridade: comprador e vendedor não podem ser o mesmo usuário
 * - Serialização JSON crítica com precisão financeira
 */
@DisplayName("MatchExecutedEvent — Evento Crítico do Motor de Match")
class MatchExecutedEventTest {

    private static ObjectMapper mapper;

    // Fixtures
    private static final UUID CORRELATION    = UUID.randomUUID();
    private static final UUID BUY_ORDER_ID   = UUID.randomUUID();
    private static final UUID SELL_ORDER_ID  = UUID.randomUUID();
    private static final UUID BUYER_USER     = UUID.randomUUID();
    private static final UUID SELLER_USER    = UUID.randomUUID();
    private static final UUID BUYER_WALLET   = UUID.randomUUID();
    private static final UUID SELLER_WALLET  = UUID.randomUUID();
    private static final BigDecimal PRICE    = new BigDecimal("157.50");
    private static final BigDecimal AMOUNT   = new BigDecimal("10.00");

    @BeforeAll
    static void setUp() {
        mapper = new ObjectMapper()
            .registerModule(new JavaTimeModule())
            .enable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
            .disable(SerializationFeature.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS)
            .disable(DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS);
    }

    private MatchExecutedEvent buildEvent(BigDecimal price, BigDecimal amount) {
        return MatchExecutedEvent.of(CORRELATION, BUY_ORDER_ID, SELL_ORDER_ID,
                BUYER_USER, SELLER_USER, BUYER_WALLET, SELLER_WALLET, price, amount);
    }

    // =========================================================================
    // Cenários de Match
    // =========================================================================
    @Nested
    @DisplayName("Cenários de Match")
    class MatchScenarios {

        @Test
        @DisplayName("match total: buyer e seller com volumes iguais")
        void fullMatch_buyerSellerSameVolume() {
            MatchExecutedEvent event = buildEvent(PRICE, AMOUNT);

            assertThat(event.matchAmount()).isEqualByComparingTo(AMOUNT);
            assertThat(event.matchPrice()).isEqualByComparingTo(PRICE);
            assertThat(event.buyOrderId()).isEqualTo(BUY_ORDER_ID);
            assertThat(event.sellOrderId()).isEqualTo(SELL_ORDER_ID);
        }

        @Test
        @DisplayName("match parcial: apenas a quantidade cruzada é registrada no evento")
        void partialMatch_onlyCrossedAmountRecorded() {
            BigDecimal buyerWants = new BigDecimal("100.00");
            BigDecimal sellerHas  = new BigDecimal("40.00");
            // O motor executa apenas o que é possível: min(100, 40) = 40
            BigDecimal executedAmount = sellerHas;

            MatchExecutedEvent event = buildEvent(PRICE, executedAmount);

            assertThat(event.matchAmount()).isEqualByComparingTo(sellerHas);
            assertThat(event.matchAmount()).isLessThan(buyerWants);
        }

        @Test
        @DisplayName("match com preço de precisão alta (simulação de mercado real)")
        void match_highPrecisionPrice() {
            BigDecimal precisePrice = new BigDecimal("157.333333");
            MatchExecutedEvent event = buildEvent(precisePrice, AMOUNT);

            assertThat(event.matchPrice()).isEqualByComparingTo(precisePrice);
        }
    }

    // =========================================================================
    // Integridade dos Dados
    // =========================================================================
    @Nested
    @DisplayName("Integridade dos Dados")
    class DataIntegrity {

        @Test
        @DisplayName("matchId deve ser gerado automaticamente e ser não-nulo")
        void matchId_autoGenerated_notNull() {
            MatchExecutedEvent event = buildEvent(PRICE, AMOUNT);
            assertThat(event.matchId()).isNotNull();
        }

        @Test
        @DisplayName("eventId e matchId devem ser UUIDs distintos")
        void eventId_and_matchId_areDifferent() {
            MatchExecutedEvent event = buildEvent(PRICE, AMOUNT);
            assertThat(event.eventId()).isNotEqualTo(event.matchId());
        }

        @Test
        @DisplayName("ambos os lados do trade devem estar presentes")
        void bothSidesOfTrade_mustBePresent() {
            MatchExecutedEvent event = buildEvent(PRICE, AMOUNT);

            assertThat(event.buyerUserId()).isNotNull().isEqualTo(BUYER_USER);
            assertThat(event.sellerUserId()).isNotNull().isEqualTo(SELLER_USER);
            assertThat(event.buyerWalletId()).isNotNull().isEqualTo(BUYER_WALLET);
            assertThat(event.sellerWalletId()).isNotNull().isEqualTo(SELLER_WALLET);
        }

        @Test
        @DisplayName("buyer e seller devem ser usuários distintos (não self-trade)")
        void buyerAndSeller_mustBeDifferentUsers() {
            MatchExecutedEvent event = buildEvent(PRICE, AMOUNT);
            assertThat(event.buyerUserId()).isNotEqualTo(event.sellerUserId());
            assertThat(event.buyerWalletId()).isNotEqualTo(event.sellerWalletId());
        }

        @Test
        @DisplayName("aggregateId deve ser o matchId (rastreabilidade no Event Store)")
        void aggregateId_shouldBeMatchId() {
            MatchExecutedEvent event = buildEvent(PRICE, AMOUNT);
            assertThat(event.aggregateId()).isEqualTo(event.matchId().toString());
        }
    }

    // =========================================================================
    // Imutabilidade (record Java)
    // =========================================================================
    @Nested
    @DisplayName("Imutabilidade do record")
    class ImmutabilityTests {

        @Test
        @DisplayName("dois eventos com mesmos dados são value-equal (record semantics)")
        void twoEvents_sameData_shouldBeEqual() {
            UUID mid = UUID.randomUUID();
            UUID eid = UUID.randomUUID();
            // Criação manual (não via factory) para controlar eventId e matchId
            MatchExecutedEvent e1 = new MatchExecutedEvent(eid, CORRELATION,
                    mid.toString(), java.time.Instant.EPOCH,
                    mid, BUY_ORDER_ID, SELL_ORDER_ID, BUYER_USER, SELLER_USER,
                    BUYER_WALLET, SELLER_WALLET, PRICE, AMOUNT);
            MatchExecutedEvent e2 = new MatchExecutedEvent(eid, CORRELATION,
                    mid.toString(), java.time.Instant.EPOCH,
                    mid, BUY_ORDER_ID, SELL_ORDER_ID, BUYER_USER, SELLER_USER,
                    BUYER_WALLET, SELLER_WALLET, PRICE, AMOUNT);

            assertThat(e1).isEqualTo(e2);
            assertThat(e1.hashCode()).isEqualTo(e2.hashCode());
        }

        @Test
        @DisplayName("eventos com matchIds distintos nunca são iguais")
        void twoEvents_differentMatchId_shouldNotBeEqual() {
            MatchExecutedEvent e1 = buildEvent(PRICE, AMOUNT);
            MatchExecutedEvent e2 = buildEvent(PRICE, AMOUNT);
            // Factory gera matchId novo — nunca devem ser iguais
            assertThat(e1.matchId()).isNotEqualTo(e2.matchId());
        }
    }

    // =========================================================================
    // Unicidade em Alta Carga (5000 trades/s)
    // =========================================================================
    @Nested
    @DisplayName("Unicidade em alta carga")
    class HighLoadUniquenessTests {

        @Test
        @DisplayName("1000 MatchExecutedEvents gerados devem ter matchIds únicos")
        void highLoad_allMatchIds_unique() {
            Set<UUID> matchIds = new HashSet<>();
            IntStream.range(0, 1000).forEach(i -> {
                MatchExecutedEvent e = buildEvent(PRICE, AMOUNT);
                matchIds.add(e.matchId());
            });
            assertThat(matchIds).hasSize(1000);
        }

        @Test
        @DisplayName("1000 MatchExecutedEvents gerados devem ter eventIds únicos")
        void highLoad_allEventIds_unique() {
            Set<UUID> eventIds = new HashSet<>();
            IntStream.range(0, 1000).forEach(i -> {
                MatchExecutedEvent e = buildEvent(PRICE, AMOUNT);
                eventIds.add(e.eventId());
            });
            assertThat(eventIds).hasSize(1000);
        }
    }

    // =========================================================================
    // Serialização JSON crítica
    // =========================================================================
    @Test
    @DisplayName("JSON serializado deve conter matchId como campo de primeiro nível")
    void json_mustContainMatchIdAtTopLevel() throws Exception {
        MatchExecutedEvent event = buildEvent(PRICE, AMOUNT);
        String json = mapper.writeValueAsString(event);

        assertThat(json).contains("matchId");
        assertThat(json).contains("buyOrderId");
        assertThat(json).contains("sellOrderId");
        assertThat(json).contains("matchPrice");
        assertThat(json).contains("matchAmount");
    }
}
